config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'homes#index'

  resources :users, only: %i[index show] do
    member do
      get :following, :followers
    end

    resources :items, expect: :index do
      resources :comments, only: :create
      resources :stocks, only: %i[create destroy]
    end
  end

  resources :tags, only: %i[show], param: :name do
    resource :follow, only: %i[create destroy], module: :tags
  end
  resources :stocks, only: :index

  resource :tagfeed, only: :show
  resource :timeline, only: :show
  resources :relationships, only: %i[create destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item

  scope :older, -> { order(created_at: :asc) }

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :stocks, dependent: :destroy
  has_many :stocker_users, through: :stocks, source: :user
  validates :title, :content, presence: true

  acts_as_ordered_taggable

  scope :recent, -> { order(updated_at: :desc) }

  scope :newer, -> { order(created_at: :desc) }

  def stock_user(user_id)
    stocks.find_by(user_id: user_id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  validates :follower_id, :followed_id, presence: true
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :user
  belongs_to :item, counter_cache: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
  has_many :stocks, dependent: :destroy
  has_many :stocked_items, through: :stocks, source: :item

  has_many :active_relationships,
           class_name: "Relationship",
           foreign_key: "follower_id",
           dependent: :destroy

  has_many :passive_relationships,
           class_name: "Relationship",
           foreign_key: "followed_id",
           dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  acts_as_ordered_taggable

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy!
  end

  def following?(other_user)
    following.include?(other_user)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  before_action :set_item

  def edit
  end

  def create
    @comment = @item.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to user_item_url(@user, @item), notice: '作成しました'
    else
      render :new
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to user_item_url(@user, @item), notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy!
    redirect_to user_item_url(@user, @item), alert: '削除しました'
  end

  private
    def set_user
      @user = User.find(params[:user_id])
    end

    def set_item
      @item = @user.items.find(params[:item_id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).recent
    @user  = current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!,only: %i(new edit update destroy)
  before_action :set_user, only: %i(show new create edit update destroy)
  before_action :set_item, only: %i(show edit update destroy)

  def show
    @comment = Comment.new
  end

  def new
    @item = Item.new
  end

  def edit
  end

  def create
    @item = @user.items.new(item_params)

    if @item.save
      redirect_to user_item_url(@user, @item), notice: '作成しました'
    else
      render :new
    end
  end

  def update
    if @item.update(item_params)
      redirect_to user_item_url(@user, @item), notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to user_url(@user), alert: '削除しました'
  end

  private
  def set_item
    @item = @user.items.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def item_params
    params.require(:item).permit(:title, :content, :tag_list)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    user = User.find(params[:followed_id])
    current_user.follow(user)
    redirect_to user
  end

  def destroy
    user = Relationship.find(params[:id]).followed
    current_user.unfollow(user)
    redirect_to user
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: %i[create destroy]

  def index
    stock_item_ids = current_user.stocks.pluck(:item_id)
    @items         = Item.where(id: stock_item_ids)
  end

  def create
    @stock = current_user.stocks.create!(item: @item)
    @item.reload
  end

  def destroy
    stock = current_user.stocks.find_by!(user: current_user, item: @item)
    stock.destroy!
    @item.reload
  end

  private
  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/tagfeeds_controller.rb
class TagfeedsController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = current_user
    @followed_tag_list = current_user.tag_list
    @items = Item.tagged_with(@followed_tag_list, any: true).newer.page(params[:page]).per(10)
  end
end

app/controllers/tags/follows_controller.rb
class Tags::FollowsController < ApplicationController
  before_action :authenticate_user!

  def create
    current_user.tag_list << tag_name
    current_user.save!
    redirect_to tag_url(tag_name)
  end


  def destroy
    current_user.tag_list.remove(tag_name)
    current_user.save!
    redirect_to tag_url(tag_name)
  end


  private

  def tag_name
    params[:tag_name]
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag_name  = params[:name]
    @items     = Item.tagged_with(@tag_name)
    @followers = User.tagged_with(@tag_name).count
  end
end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController
  before_action :authenticate_user!

  def show
    following_user_ids = current_user.following.pluck(:id)
    @items             = Item.where(user_id: following_user_ids).page(params[:page]).recent
    @user              = current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: :show

  def index
    @users = User.page(params[:page]).order(:name)
  end

  def show
    @items = @user.items.recent
    @stocked_items = @user.stocked_items.recent
  end

  def following
    @user = User.find(params[:id])
    @users = @user.following.order(:name).page(params[:page])
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers.order(:name).page(params[:page])
    render 'show_follow'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_list.html.haml
%h3 コメント一覧
%ul.list-group
  - item.comments.older.includes(:user).each do |comment|
    %li.list-group-item
      - user = comment.user
      = link_to user.name, user_path(user)
      = l comment.created_at
      %br
      = comment.content
      %div{ id: "like-comment-form-#{comment.id}" }
        = render 'comments/likes/like', comment: comment if comment.user != current_user

app/views/comments/_form.html.haml
= form_with(model: [user, item, comment], local: true) do |f|
  - if comment.errors.any?
    #error_explanation.alert.alert-danger
      %ul
        - comment.errors.full_messages.each do |message|
          %li #{message}

  .field
    = f.text_area :content, id: :comment_content, placeholder: "コメント内容", class: 'form-control'

  .actions.text-right
    = f.submit (yield :submit_label), class: 'btn btn-primary mt-1'

app/views/comments/edit.html.haml
- provide :submit_label, "更新"
= render 'form', user: @user, item: @item, comment: @comment

app/views/comments/new.html.haml
- provide :submit_label, "投稿する"
= render 'comments/form', user: @user, item: @item, comment: @comment

app/views/homes/index.html.haml
.row
  %aside.col-md-4
    = render 'shared/nav_left', items: @stocked_items
  .col-md-5
    = render 'items/item_list', items: @items
  %aside.col-md-3
    = render 'shared/user_info', user: @user

app/views/items/_form.html.haml
= form_with(model: [user, item], local: true) do |f|
  - if item.errors.any?
    #error_explanation.alert.alert-danger
      %ul
        - item.errors.full_messages.each do |message|
          %li #{message}

  .field
    = f.text_field :title, id: :item_title, placeholder: "タイトル", class: 'form-control'

  .field.mt-1
    = f.text_field :tag_list, id: :item_tag, placeholder: "タグ", class: 'form-control'

  .row.mt-3
    .col-md-6
      .card
        .card-header 本文
        = f.text_area :content, id: :item_content, placeholder: "本文", class: 'form-control'
  .actions.text-right
    = f.submit (yield :submit_label), class: 'btn btn-primary mt-1'

app/views/items/_item_list.html.haml
%ol.items.list-group
  - items.each do |item|
    %li.list-group-item
      =link_to item.title, user_item_path(item.user, item)
      %span.pull-right= l item.updated_at, format: :short_slash

app/views/items/_tag_list.html.haml
%ul.nav.nav-pills
  - tag_list.each do |tag|
    %li.nav-item.mr-1
      = link_to tag, tag_path(tag), class: "btn btn-sm btn-light", role: "button"

app/views/items/_tag_list_links.html.haml
- tag_list.each_with_index do |tag, i|
  =link_to tag, tag_path(tag)
  - if i < tag_list.size - 1
    ,

app/views/items/edit.html.haml
- provide :submit_label, "更新"
= render 'form', user: @user, item: @item

app/views/items/new.html.haml
- provide :submit_label, "投稿する"
= render 'form', user: @user, item: @item

app/views/items/show.html.haml
#stock-buttons-form
  = render "stocks/stock", item: @item


.container
  %h1.item-title= @item.title

  = link_to @user.name, user_path(@user)
  #{l @item.updated_at, format: :short} に更新
  - if user_signed_in? && @user == current_user
    = link_to '編集する', edit_user_item_path(@user, @item)
    = link_to '削除する', user_item_path(@user, @item), method: :delete, data: {confirm: 'よろしいですか？'}

  .item-tags= render 'items/tag_list', tag_list: @item.tag_list
  .item-content= @item.content
  #like-buttons-form
    -#= render 'items/likes/like', item: @item if @item.user != current_user
  %hr
  = render "comments/comment_list", item: @item

  - if user_signed_in?
    = render template: "comments/new"
  - else
    あなたのもコメントしてみませんか
    %br
    = link_to 'ユーザー登録', new_user_registration_path, class: "btn btn-success"
    %br
    すでにアカウントを持っている方は
    = link_to 'ログイン', new_user_session_path, class: "btn btn-link"

app/views/layouts/_header.html.haml
%header
  %nav.navbar.navbar-expand-md
    = link_to 'Atiiq', root_path, class: 'navbar-brand'

    %button.navbar-toggler{type:"button", data:{toggle:"collapse", target:"#mainNavbarCollapse"}}= '&#9776;'.html_safe
    #mainNavbarCollapse.collapse.navbar-collapse.ml-auto
      %ul.navbar-nav.ml-auto
        - if user_signed_in?
          %li.nav-item.dropdown
            = link_to 'コミュニティ', '#', id: 'navbarDropdown', role: "button", data: {toggle: "dropdown"},  class: "nav-link dropdown-toggle"
            .dropdown-menu{ aria: { labelledby: "navbarDropdown" } }
              =link_to 'ユーザー一覧', users_path, class:"dropdown-item"
          %li.nav-item
            = link_to 'ストック一覧', stocks_path ,class:"nav-link"

          %li.nav-item
            = link_to '投稿する', new_user_item_path(current_user) ,class:"nav-link"
          %li.nav-item
            = link_to '記事の一覧', user_path(current_user) ,class:"nav-link"
          %li.nav-item
            = link_to 'ログアウト', destroy_user_session_path, method: :delete ,class:"nav-link"
        - else
          %li.nav-item
            = link_to 'ユーザー登録', new_user_registration_path ,class:"nav-link"
          %li.nav-item
            = link_to 'ログイン', new_user_session_path, class:"nav-link"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Atiiq2
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    .container.mt-3
      - if notice
        %p.alert.alert-success= notice
      - if alert
        %p.alert.alert-danger= alert
      = yield

app/views/shared/_feed.html.haml
- if items.any?
  %h4 投稿一覧（#{items.count}）
  = render 'items/item_list', items: items
- else
  %h4 投稿はありません

app/views/shared/_nav_left.html.haml
- if current_user == @user
  %section.timeline
    = link_to "タイムライン", timeline_path
  %section.tags_feed
    = link_to "タグフィード", tagfeed_path

app/views/shared/_stats.html.haml
- if user
  .stats
    %a{ href: following_user_path(user) }
      %strong#following.stat
        = user.following.count
      フォロー
    %a{ href: followers_user_path(user) }
      %strong#followers.stat
        = user.followers.count
      フォロワー

app/views/shared/_user_info.html.haml
- if @user
  %section.user_info
    %h1
      = user.name
  %section.stats
    = render 'shared/stats', user: @user

app/views/stocks/_stock.html.haml
- if user_signed_in? && current_user != item.user
  - if stock = item.stock_user(current_user.id)
    = button_to user_item_stock_path(item.user, item, stock), class: "btn btn-danger", method: :delete, id: "stock-button", remote: true do
      ストック解除
      %span.badge.badge-light #{item.stocks_count}
  - else
    = button_to user_item_stocks_path(item.user, item), class: "btn btn-success", id: "stock-button", remote: true do
      ストックする
      %span.badge.badge-light #{item.stocks_count}

app/views/stocks/_stock_list.html.haml
%ol.items.list-group
  - items.each do |item|
    %li.list-group-item
      .row
        =link_to item.user.name, user_path(item.user)
        が
        %span= l item.updated_at, format: :short_slash
        に投稿

      .row
        = link_to item.title, user_item_path(item.user, item)
      .row
        =render "items/tag_list", tag_list: item.tag_list

app/views/stocks/create.js.erb
$("#stock-buttons-form").html("<%= j(render partial: 'stock', locals: { item: @item, stock: @stock }) %>")

app/views/stocks/destroy.js.erb
$("#stock-buttons-form").html("<%= j(render partial: 'stock', locals: { item: @item }) %>")

app/views/stocks/index.html.haml
.row
  %aside.col-md-4
    %h4 ストック一覧
    あなたがストックした記事の一覧です。
    %h5 ストック内検索
    %h5 タグ

  .col-md-8
    - if @items.any?
      %h3 ストック一覧（#{@items.count}）
      = render 'stock_list', items: @items
    - else
      %h3 ストックはありません

app/views/tagfeeds/_tagfeed.html.haml
- if items.any?
  %h4 タグフィード

  .paginate= paginate @items

  %ol.items.list-group
    - items.each do |item|
      %li.list-group-item
        - matched_tag = (item.tag_list & @followed_tag_list).first
        .tag
          %code= matched_tag
        = link_to item.title, user_item_path(item.user, item)

app/views/tagfeeds/show.html.haml
.row
  %aside.col-md-4
    = render 'shared/nav_left', items: @stocked_items
  .col-md-5
    = render 'tagfeed', items: @items
  %aside.col-md-3
    = render 'shared/user_info', user: @user

app/views/tags/_feed.html.haml
- if tag_list && tag_list.count > 0
  %h4 フォロー中のタグ
  %ol.tag_list.list-group
    - tag_list.each do |tag|
      %li.list-group-item
        = link_to tag, tag_path(name: tag)
- else
  %h4 タグをフォローしていません

app/views/tags/_follow_form.html.haml
#follow_form
  - if current_user.tag_list.include?(tag_name)
    = button_to "フォロー解除", tag_follow_path(tag_name), method: :delete, class: "btn btn-danger"
  - else
    = button_to "フォロー", tag_follow_path(tag_name: tag_name), class: "btn btn-light"

app/views/tags/show.html.haml
%h1 #{@tag_name} タグのついている記事一覧
= "#{@items.count} 記事"
= "#{@followers} フォロワー"
= render 'follow_form', tag_name: @tag_name if current_user
%h3
%ul.list-group
  - @items.each do |item|
    %li.list-group-item
      = link_to "#{item.title}", user_item_path(item.user, item)

app/views/timelines/show.html.haml
.row
  %aside.col-md-2
    = render 'shared/nav_left', items: @stocked_items

  .col-md-7
    %h3 タイムライン
    %ol.items.list-group
      - @items.each do |item|
        %li.list-group-item
          .row
            #{item.user.name} が投稿しました
            %span.pull-right= l item.updated_at, format: :short_slash
          .row
            = link_to item.title, user_item_path(item.user, item)
          .row
            =render "items/tag_list_links", tag_list: item.tag_list

  %aside.col-md-3
    = render 'shared/user_info', user: @user

app/views/users/_follow.html.haml
= form_for(current_user.active_relationships.build) do |f|
  %div
    = hidden_field_tag :followed_id, user.id
  = f.submit "フォロー", class: "btn btn-primary"

app/views/users/_follow_form.html.haml
#follow_form
  - if current_user.following?(user)
    = render 'unfollow', user: user
  - else
    = render 'follow', user: user

app/views/users/_unfollow.html.haml
= form_for(current_user.active_relationships.find_by(followed_id: user.id), html: { method: :delete }) do |f|
  = f.submit "フォロー解除", class: "btn btn-danger"

app/views/users/_user.html.haml
%li.list-group-item
  = link_to "#{user.name}", user_path(user)

app/views/users/index.html.haml
= paginate @users

%ul.list-group.mb-3
    = render @users

= paginate @users

app/views/users/show.html.haml
.row
  %aside.col-md-2
    = render 'shared/nav_left', items: @stocked_items

  .col-md-7
    = render 'follow_form', user: @user if current_user && current_user != @user
    = render 'shared/feed', items: @items
  %aside.col-md-3
    = render 'shared/user_info', user: @user

app/views/users/show_follow.html.haml
.row
  %aside.col-md-4
    %section.user_info
      %h1= @user.name
      %span= link_to "プロフィール", user_path(@user)
      %span
        %strong Posts
        = @user.items.count
    %section.stats
      = render 'shared/stats', user: @user
  .col-md-8
    %h3= @title
    - if @users.any?
      %ul.users.follow
        = render @users
      = paginate @users